

database:
  # Available: MySQL, SQLite
  # Upon changing the database type, the data won"t be converted
  type: SQLite
  table: dcroles
  # Rest is only required when using MySQL
  address: 127.0.0.1:3306
  name: XXX
  username: XXX
  password: XXX

commands:
  dccode:
    function: SHOW_CODE
    permissionSelf: dcr.dccode.self
    permissionOthers: dcr.dccode.others