bot:
  token: XXX
  giveRankName: "giverank"
  commandDescription: "Uzyskaj rangę z serwera Minecraft"
  mcNameOption: Twój nick Minecraft
  codeOption: Twój kod z '/dccode'

sql:
  # MySQL or SQLite
  # Upon changing the database type, the user data will not be saved
  type: SQLite
  # The rest is only required when using MySQL
  dbAddress: 127.0.0.1:3306
  dbUsername: root
  dbPassword: XXX

text:
  # PREFIX - {P}
  prefix: "<#0039D1>&lD<#111DE8>&lC<#2200FF>&lR &8» &r"
  # Replaces 'default' value from database (By default to 'Gracz')
  defualtRoleReplace: "Gracz"
  # Null value
  null: Brak
  # Code manage inventory name
  codeManageInvName: "<#0039D1>&lM<#003FD5>&le<#0045D9>&ln<#004ADE>&le<#0050E2>&ld<#0056E6>&lż<#005CEA>&le<#0062EE>&lr <#0068F2>&lk<#006DF7>&lo<#0073FB>&ld<#0079FF>&lu"


messages:
  # HEX - <#XXXXXX>
  # Plugin start
  pluginEnabling: "{P}&9 Włączanie pluginu..."
  pluginDisabling: "{P}&9 Wyłączanie pluginu..."
  pluginEnabled: "{P}&7 {PLUGIN} &azostał włączony!"
  pluginDisabled: "{P}&c Coś poszło nie tak! Popraw błędy i przeładuj plugin."
  botLoaded: "{P}&a Bot został załadowany &8[&7{BOTNAME}&8]"
  playerNotFound: "{P}&c Nie znaleziono takiego gracza"
  executorNotPlayer: "{P}&c Tylko gracz może to zrobić"
  removedUser: "{P}&f Pomyślnie usunięto gracza &7{USER}"
  helpFormat:
    - "&8≡≡═════ {P} &8═════≡≡"
    - "{P} &9/dccode &8-&f Pokazuje kod użytkownika"
    - "&8≡≡═════ {P} &8═════≡≡"
  firstJoin:
    - "{P} &7Nadano rangę&f {RANK}"
    - "{P} &7Wygenerowano kod:&f {CODE}"
  # DCRCode output, when showing sender's code
  selfDCCode:
    - "{P} <#1FFDFD>Twój kod:"
    - "{P} <click:copy_to_clipboard:{CODE}><hover:show_text:\"<u>Kliknij, aby skopiować\"><#FFFFFF>{CODE}"
  # DCCode output, when showing other person's code
  argDCCode:
    - "{P} <#1FFDFD>Kod&7 {USER}:"
    - "{P} <click:copy_to_clipboard:{CODE}><hover:show_text:\"<u>Kliknij, aby skopiować\"><#FFFFFF>{CODE}"

  noPermission: "{P}&c Nie masz permisji."
